In [53]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [54]:
df = pd.read_csv("D:\\IIT\\2nd Year\\Group project\\model\\database.csv")
df.head(20)

C:\Users\Chethaka\AppData\Local\Temp\ipykernel_38732\836050448.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("D:\\IIT\\2nd Year\\Group project\\model\\database.csv")

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
5,6,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,1,Murder or Manslaughter,...,Unknown,Male,36,White,Unknown,Acquaintance,Rifle,0,0,FBI
6,7,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,2,Murder or Manslaughter,...,Unknown,Male,27,Black,Unknown,Wife,Knife,0,0,FBI
7,8,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,June,1,Murder or Manslaughter,...,Unknown,Male,35,White,Unknown,Wife,Knife,0,0,FBI
8,9,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,June,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Firearm,0,0,FBI
9,10,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,June,3,Murder or Manslaughter,...,Unknown,Male,40,Unknown,Unknown,Unknown,Firearm,0,1,FBI
10,11,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,July,1,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
11,12,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,July,2,Murder or Manslaughter,...,Unknown,Male,49,White,Unknown,Stranger,Shotgun,0,0,FBI
12,13,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,July,3,Murder or Manslaughter,...,Unknown,Male,39,Black,Unknown,Girlfriend,Blunt Object,0,0,FBI
13,14,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,August,1,Murder or Manslaughter,...,Unknown,Male,49,White,Unknown,Unknown,Fall,0,0,FBI
14,15,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,August,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
15,16,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,August,3,Murder or Manslaughter,...,Unknown,Female,29,Black,Unknown,Ex-Husband,Handgun,0,0,FBI
16,17,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,December,1,Murder or Manslaughter,...,Unknown,Male,19,Unknown,Unknown,Acquaintance,Knife,0,0,FBI
17,18,AK00103,Juneau,Municipal Police,Juneau,Alaska,1980,November,1,Murder or Manslaughter,...,Unknown,Male,23,Native American/Alaska Native,Unknown,Brother,Blunt Object,0,1,FBI
18,19,AK00106,Nome,Municipal Police,Nome,Alaska,1980,June,1,Murder or Manslaughter,...,Unknown,Male,33,Native American/Alaska Native,Unknown,Acquaintance,Handgun,0,0,FBI
19,20,AK00113,Bethel,Municipal Police,Bethel,Alaska,1980,February,1,Murder or Manslaughter,...,Unknown,Male,35,Native American/Alaska Native,Unknown,Brother,Handgun,0,0,FBI

In [55]:
df.shape

(638454, 24)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638454 entries, 0 to 638453
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Record ID              638454 non-null  int64
 1   Agency Code            638454 non-null  object
 2   Agency Name            638454 non-null  object
 3   Agency Type            638454 non-null  object
 4   City                   638454 non-null  object
 5   State                  638454 non-null  object
 6   Year                   638454 non-null  int64
 7   Month                  638454 non-null  object
 8   Incident               638454 non-null  int64
 9   Crime Type             638454 non-null  object
 10  Crime Solved           638454 non-null  object
 11  Victim Sex             638454 non-null  object
 12  Victim Age             638454 non-null  int64
 13  Victim Race            638454 non-null  object
 14  Victim Ethnicity       638454 non-null  object
 15  Perpetrator Sex        638454 non-null  object
 16  Perpetrator Age        638454 non-null  object
 17  Perpetrator Race       638454 non-null  object
 18  Perpetrator Ethnicity  638454 non-null  object
 19  Relationship           638454 non-null  object
 20  Weapon                 638454 non-null  object
 21  Victim Count           638454 non-null  int64
 22  Perpetrator Count      638454 non-null  int64
 23  Record Source          638454 non-null  object
dtypes: int64(6), object(18)
memory usage: 116.9+ MB

Dataset Preprocessing

In [57]:
df.drop(['Record ID'],axis=1, inplace=True) #Since year is not doing much thing in the prediction
df.drop(['Agency Code'],axis=1, inplace=True)
df.drop(['Agency Name'],axis=1, inplace=True)
df.drop(['Agency Type'],axis=1, inplace=True)
df.drop(['Crime Solved'],axis=1, inplace=True)
df.drop(['Record Source'],axis=1, inplace=True)

In [58]:
cat_features = []

for column in df.select_dtypes(include=object).columns:
        cat_features.append(column)

for cat_featurer in cat_features:
    print(cat_featurer)

City
State
Month
Crime Type
Victim Sex
Victim Race
Victim Ethnicity
Perpetrator Sex
Perpetrator Age
Perpetrator Race
Perpetrator Ethnicity
Relationship
Weapon

In [59]:
duplicated_rows = df.duplicated().tolist()
df[duplicated_rows].count()

City                     2199
State                    2199
Year                     2199
Month                    2199
Incident                 2199
Crime Type               2199
Victim Sex               2199
Victim Age               2199
Victim Race              2199
Victim Ethnicity         2199
Perpetrator Sex          2199
Perpetrator Age          2199
Perpetrator Race         2199
Perpetrator Ethnicity    2199
Relationship             2199
Weapon                   2199
Victim Count             2199
Perpetrator Count        2199
dtype: int64

In [60]:
df.drop_duplicates(inplace=True)

In [61]:
df.shape

(636255, 18)

In [62]:
for cat_feature in cat_features:
    print(cat_feature)
    print(df[cat_feature].unique())

City
['Anchorage' 'Juneau' 'Nome' ... 'Rooks' 'McCone' 'Antelope']
State
['Alaska' 'Alabama' 'Arkansas' 'Arizona' 'California' 'Colorado'
 'Connecticut' 'District of Columbia' 'Delaware' 'Florida' 'Georgia'
 'Hawaii' 'Iowa' 'Idaho' 'Illinois' 'Indiana' 'Kansas' 'Kentucky'
 'Louisiana' 'Massachusetts' 'Maryland' 'Maine' 'Michigan' 'Minnesota'
 'Missouri' 'Mississippi' 'Montana' 'Nebraska' 'North Carolina'
 'North Dakota' 'New Hampshire' 'New Jersey' 'New Mexico' 'Nevada'
 'New York' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhodes Island'
 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Virginia'
 'Vermont' 'Washington' 'Wisconsin' 'West Virginia' 'Wyoming']
Month
['January' 'March' 'April' 'May' 'June' 'July' 'August' 'December'
 'November' 'February' 'October' 'September']
Crime Type
['Murder or Manslaughter' 'Manslaughter by Negligence']
Victim Sex
['Male' 'Female' 'Unknown']
Victim Race
['Native American/Alaska Native' 'White' 'Black' 'Unknown'
 'Asian/Pacific Islander']
Victim Ethnicity
['Unknown' 'Not Hispanic' 'Hispanic']
Perpetrator Sex
['Male' 'Unknown' 'Female']
Perpetrator Age
[15 42 0 36 27 35 40 49 39 29 19 23 33 26 41 28 61 25 7 17 34 21 43 38 66
 32 37 22 30 24 65 51 60 45 64 18 20 44 73 62 69 52 16 90 56 47 57 31 46
 14 55 50 54 68 77 53 67 48 76 58 71 63 89 13 75 72 93 59 10 11 79 74 99
 70 78 80 9 12 81 6 87 82 83 8 84 85 86 5 3 1 88 95 4 91 92 96 94 2 98 97
 '22' '52' '21' '0' '25' '61' '32' '28' '20' '38' '18' '17' '53' '30' '24'
 '84' '43' '16' '47' '54' '50' '42' '23' '36' '35' '60' '27' '19' '14'
 '57' '63' '81' '31' '58' '51' '15' '40' '33' '26' '41' '29' '34' '37'
 '69' '44' '48' '55' '49' '56' '39' '45' '65' '59' '70' '46' '11' '77'
 '67' '76' '85' '72' '13' '89' '74' '71' '64' '62' '3' '80' '73' '75' '83'
 '78' '68' '66' '86' '87' '95' '90' '6' '12' '99' '88' '9' '93' '10' ' '
 '82' '92' '79' '1']
Perpetrator Race
['Native American/Alaska Native' 'White' 'Unknown' 'Black'
 'Asian/Pacific Islander']
Perpetrator Ethnicity
['Unknown' 'Not Hispanic' 'Hispanic']
Relationship
['Acquaintance' 'Unknown' 'Wife' 'Stranger' 'Girlfriend' 'Ex-Husband'
 'Brother' 'Stepdaughter' 'Husband' 'Sister' 'Friend' 'Family' 'Neighbor'
 'Father' 'In-Law' 'Son' 'Ex-Wife' 'Boyfriend' 'Mother'
 'Common-Law Husband' 'Common-Law Wife' 'Stepfather' 'Stepson'
 'Stepmother' 'Daughter' 'Boyfriend/Girlfriend' 'Employer' 'Employee']
Weapon
['Blunt Object' 'Strangulation' 'Unknown' 'Rifle' 'Knife' 'Firearm'
 'Shotgun' 'Fall' 'Handgun' 'Drowning' 'Suffocation' 'Explosives' 'Fire'
 'Drugs' 'Gun' 'Poison']

In [67]:
df['Perpetrator Age'].max()

TypeError: '>=' not supported between instances of 'int' and 'str'

In [13]:
df.drop(['ethnic1r'],inplace=True,axis=1) #Repating the same data

In [14]:
df.head(10)

,weight,gender,race1r,hispanic,age,marital2,hincome,popsize,region,msa,...,notify,weapon,weapcat,newcrime,newoff,seriousviolent,injury,treatment,vicservices,locationr
0,8442.41411,Female,White,Non-Hispanic,65+,Divorced,"$25,000 to $34,999",Unknown,-1,Urban,...,1,Unknown if offender had weapon,Do not know if offender had weapon,Personal Theft/Larceny,5,Unknown,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
1,5158.88511,Female,White,Non-Hispanic,35-49,Married,"$25,000 to $34,999",Unknown,-1,Suburban,...,2,No weapon,No weapon,Violent Victimization,2,Yes,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
2,3006.10621,Female,Black,Non-Hispanic,25-34,Never married,"$7,500 to $14,999",Unknown,-1,Rural,...,1,No weapon,No weapon,Violent Victimization,4,No,Injured,Not treated for injury,Services received from victim services agencies,At or near victim's home
3,4533.87724,Male,White,Non-Hispanic,21-24,Married,"$50,000 to $74,999",Unknown,-1,Suburban,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
6,8381.88322,Female,White,Hispanic,50-64,Divorced,"$50,000 to $74,999",Unknown,-1,Suburban,...,1,"Yes, weapon",Firearm,Violent Victimization,3,Yes,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
7,4945.82108,Male,Black,Non-Hispanic,35-49,Separated,"Less than $7,500",Unknown,-1,Urban,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
8,41553.83070,Male,White,Non-Hispanic,25-34,Married,"$25,000 to $34,999",Unknown,-1,Suburban,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
9,3877.56841,Female,Black,Non-Hispanic,18-20,Never married,"Less than $7,500",Unknown,-1,Urban,...,1,"Yes, weapon",Other type of weapon,Violent Victimization,3,Yes,Injured,Not treated for injury,No services received,"at or near friend, neighbor, or relative's home"
10,4276.40376,Female,White,Non-Hispanic,35-49,Married,"$75,000 or more",Unknown,-1,Suburban,...,2,"Yes, weapon",Other type of weapon,Violent Victimization,3,Yes,Injured,Not treated for injury,No services received,At or near victim's home
11,5844.94141,Female,White,Non-Hispanic,21-24,Divorced,"Less than $7,500",Unknown,-1,Suburban,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."

In [15]:
(df['hispanic']=='88').sum()

385

In [16]:
df.drop('vicservices',inplace=True,axis=1)

In [20]:
target_columns = df[['age','marital2']]