In [50]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [51]:
df = pd.read_csv("D:\\IIT\\2nd Year\\Group project\\model\\demographic.csv")
df.head(20)

,year,weight,gender,race1r,hispanic,ethnic1r,age,marital2,hincome,popsize,...,notify,weapon,weapcat,newcrime,newoff,seriousviolent,injury,treatment,vicservices,locationr
0,2014.0,8442.41411,Female,White,Non-Hispanic,Non-Hispanic White,65+,Divorced,"$25,000 to $34,999",Unknown,...,1,Unknown if offender had weapon,Do not know if offender had weapon,Personal Theft/Larceny,5,Unknown,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
1,2014.0,5158.88511,Female,White,Non-Hispanic,Non-Hispanic White,35-49,Married,"$25,000 to $34,999",Unknown,...,2,No weapon,No weapon,Violent Victimization,2,Yes,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
2,2014.0,3006.10621,Female,"Black, 3: Other (this includes American Indian...",Non-Hispanic,Non-Hispanic Black,25-34,Never married,"$7,500 to $14,999",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Injured,Not treated for injury,Services received from victim services agencies,At or near victim's home
3,2014.0,4533.87724,Male,White,Non-Hispanic,Non-Hispanic White,21-24,Married,"$50,000 to $74,999",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
4,2014.0,4533.87724,Male,White,Non-Hispanic,Non-Hispanic White,21-24,Married,"$50,000 to $74,999",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
5,2014.0,4533.87724,Male,White,Non-Hispanic,Non-Hispanic White,21-24,Married,"$50,000 to $74,999",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
6,2014.0,8381.88322,Female,White,Hispanic,Hispanic,50-64,Divorced,"$50,000 to $74,999",Unknown,...,1,"Yes, weapon",Firearm,Violent Victimization,3,Yes,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
7,2014.0,4945.82108,Male,"Black, 3: Other (this includes American Indian...",Non-Hispanic,Non-Hispanic Black,35-49,Separated,"Less than $7,500",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
8,2014.0,41553.83070,Male,White,Non-Hispanic,Non-Hispanic White,25-34,Married,"$25,000 to $34,999",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
9,2014.0,3877.56841,Female,"Black, 3: Other (this includes American Indian...",Non-Hispanic,Non-Hispanic Black,18-20,Never married,"Less than $7,500",Unknown,...,1,"Yes, weapon",Other type of weapon,Violent Victimization,3,Yes,Injured,Not treated for injury,No services received,"at or near friend, neighbor, or relative's home"
10,2014.0,4276.40376,Female,White,Non-Hispanic,Non-Hispanic White,35-49,Married,"$75,000 or more",Unknown,...,2,"Yes, weapon",Other type of weapon,Violent Victimization,3,Yes,Injured,Not treated for injury,No services received,At or near victim's home
11,2014.0,5844.94141,Female,White,Non-Hispanic,Non-Hispanic White,21-24,Divorced,"Less than $7,500",Unknown,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
12,2014.0,6575.23570,Male,White,Non-Hispanic,Non-Hispanic White,25-34,Never married,"$50,000 to $74,999",Unknown,...,1,"Yes, weapon",Other type of weapon,Violent Victimization,2,Yes,Injured,"Treated at scene, home, medical office or othe...",Services received from victim services agencies,"Commercial place, parking lot, or other public..."
13,2014.0,3700.63616,Male,White,Non-Hispanic,Non-Hispanic White,15-17,Never married,"$15,000 to $24,999",Unknown,...,3,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
14,2014.0,3700.63616,Male,White,Non-Hispanic,Non-Hispanic White,15-17,Never married,"$15,000 to $24,999",Unknown,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,School
15,2014.0,3700.63616,Male,White,Non-Hispanic,Non-Hispanic White,15-17,Never married,"$15,000 to $24,999",Unknown,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,At or near victim's home
16,2014.0,3700.63616,Male,White,Non-Hispanic,Non-Hispanic White,15-17,Never married,"$15,000 to $24,999",Unknown,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,School
17,2014.0,3820.47612,Female,White,Non-Hispanic,Non-Hispanic White,25-34,Married,"$25,000 to $34,999",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Injured,"Treated at scene, home, medical office or othe...",No services received,At or near victim's home
18,2014.0,5284.48537,Female,White,Non-Hispanic,Non-Hispanic White,25-34,Separated,"Less than $7,500",Unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Injured,Not treated for injury,No services received,At or near victim's home
19,2014.0,2504.86869,Female,White,Non-Hispanic,Non-Hispanic White,12-14,Never married,"$75,000 or more",Unknown,...,2,Unknown if offender had weapon,Do not know if offender had weapon,Personal Theft/Larceny,5,Unknown,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."

In [52]:
df.shape

(49717, 23)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49717 entries, 0 to 49716
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            49717 non-null  float64
 1   weight          49717 non-null  float64
 2   gender          49717 non-null  object
 3   race1r          49717 non-null  object
 4   hispanic        49717 non-null  object
 5   ethnic1r        49717 non-null  object
 6   age             49717 non-null  object
 7   marital2        49717 non-null  object
 8   hincome         49717 non-null  object
 9   popsize         49717 non-null  object
 10  region          49717 non-null  object
 11  msa             49717 non-null  object
 12  direl           49717 non-null  object
 13  notify          49717 non-null  int64
 14  weapon          49717 non-null  object
 15  weapcat         49717 non-null  object
 16  newcrime        49717 non-null  object
 17  newoff          49717 non-null  int64
 18  seriousviolent  49717 non-null  object
 19  injury          49717 non-null  object
 20  treatment       49717 non-null  object
 21  vicservices     49717 non-null  object
 22  locationr       49717 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 8.7+ MB

Dataset Preprocessing

In [54]:
df.drop(['year'],axis=1, inplace=True) #Since year is not doing much thing in the prediction

In [55]:
cat_features = []

for column in df.select_dtypes(include=object).columns:
        cat_features.append(column)

for cat_featurer in cat_features:
    print(cat_featurer)

df['age'].unique().size

gender
race1r
hispanic
ethnic1r
age
marital2
hincome
popsize
region
msa
direl
weapon
weapcat
newcrime
seriousviolent
injury
treatment
vicservices
locationr

8

In [56]:
duplicated_rows = df.duplicated().tolist()
df[duplicated_rows]

,weight,gender,race1r,hispanic,ethnic1r,age,marital2,hincome,popsize,region,...,notify,weapon,weapcat,newcrime,newoff,seriousviolent,injury,treatment,vicservices,locationr
4,4533.87724,Male,White,Non-Hispanic,Non-Hispanic White,21-24,Married,"$50,000 to $74,999",Unknown,-1,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
5,4533.87724,Male,White,Non-Hispanic,Non-Hispanic White,21-24,Married,"$50,000 to $74,999",Unknown,-1,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
16,3700.63616,Male,White,Non-Hispanic,Non-Hispanic White,15-17,Never married,"$15,000 to $24,999",Unknown,-1,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,School
38,3174.84103,Female,White,Non-Hispanic,Non-Hispanic White,21-24,Never married,"$25,000 to $34,999",Unknown,-1,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,Other location
112,9892.74529,Male,"Black, 3: Other (this includes American Indian...",Non-Hispanic,Non-Hispanic Black,35-49,Married,"$25,000 to $34,999",Unknown,-1,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"Commercial place, parking lot, or other public..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49676,3746.75691,Female,White,Non-Hispanic,Non-Hispanic White,21-24,Never married,88,"Under 100,000",South,...,2,No weapon,No weapon,Violent Victimization,4,No,Injured,Not treated for injury,No services received,At or near victim's home
49677,3746.75691,Female,White,Non-Hispanic,Non-Hispanic White,21-24,Never married,88,"Under 100,000",South,...,2,No weapon,No weapon,Violent Victimization,4,No,Injured,Not treated for injury,No services received,At or near victim's home
49689,3153.77871,Male,White,Non-Hispanic,Non-Hispanic White,50-64,Divorced,88,"Under 100,000",unknown,...,1,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,At or near victim's home
49704,2341.50039,Female,3,Non-Hispanic,Non-Hispanic Other,65+,Widowed,"$15,000 to $24,999",Not a place,unknown,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"at or near friend, neighbor, or relative's home"
49705,2341.50039,Female,3,Non-Hispanic,Non-Hispanic Other,65+,Widowed,"$15,000 to $24,999",Not a place,unknown,...,2,No weapon,No weapon,Violent Victimization,4,No,Not injured,Not injured,No services received,"at or near friend, neighbor, or relative's home"

In [57]:
df.drop_duplicates(inplace=True)

In [58]:
df.shape

(47197, 22)

In [63]:
for cat_feature in cat_features:
    print(cat_feature)
    print(df[cat_feature].unique())

gender
['Female' 'Male']
race1r
['White'
 'Black, 3: Other (this includes American Indians and Alaska Natives' '3']
hispanic
['Non-Hispanic' 'Hispanic' '88']
ethnic1r
['Non-Hispanic White' 'Non-Hispanic Black' 'Hispanic' 'Non-Hispanic Other']
age
['65+' '35-49' '25-34' '21-24' '50-64' '18-20' '15-17' '12-14']
marital2
['Divorced' 'Married' 'Never married' 'Separated' 'Widowed' '88']
hincome
['$25,000 to $34,999' '$7,500 to $14,999' '$50,000 to $74,999'
 'Less than $7,500' '$75,000 or more' '$15,000 to $24,999'
 '$35,000 to $49,999' '88']
popsize
['Unknown' 'Not a place' '250,000-499,999' '100,000-249,999'
 'Under 100,000' '1 million or more' '500,000-999,999']
region
['-1' 'unknown' 'West' 'South' 'Midwest']
msa
['Urban' 'Suburban' 'Rural']
direl
['Stranger' 'Other relatives' 'Well known/casual acquantances' '1.0'
 'Unknown number of offenders' 'Unknown relationship' 'Unknown']
weapon
['Unknown if offender had weapon' 'No weapon' 'Yes, weapon']
weapcat
['Do not know if offender had weapon' 'No weapon' 'Firearm'
 'Other type of weapon' 'Knife' 'Type weapon unknown']
newcrime
['Personal Theft/Larceny' 'Violent Victimization']
seriousviolent
['Unknown' 'Yes' 'No']
injury
['Not injured' 'Injured']
treatment
['Not injured' 'Not treated for injury'
 'Treated at scene, home, medical office or other location' 'Unknown']
vicservices
['No services received' 'Services received from victim services agencies'
 'Unknown']
locationr
['Commercial place, parking lot, or other public area'
 "At or near victim's home" 'Other location'
 "at or near friend, neighbor, or relative's home" 'School']

In [70]:
df['race1r'] = df['race1r'].apply(lambda x: "Black" if x == "Black, 3: Other (this includes American Indians and Alaska Natives" or x == "3" else x)
df['race1r']

df['race1r'].unique()

array(['White', 'Black'], dtype=object)